# Generated by Django 3.2.15 on 2022-10-29 09:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0002_file_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=57, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=3035)),
                ('convex_hull', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=3035)),
                ('csv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='files.file')),
                ('gpkg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='files.file')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=3035)),
                ('in_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.country')),
            ],
            options={
                'unique_together': {('name', 'in_country')},
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=3035)),
                ('in_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.country')),
                ('in_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.region')),
            ],
            options={
                'unique_together': {('name', 'in_region')},
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('id_source', models.CharField(max_length=80)),
                ('height', models.FloatField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('type', models.CharField(choices=[('RE', 'residential'), ('NR', 'non − residential'), ('UN', 'unknown')], default='UN', max_length=2)),
                ('type_source', models.CharField(max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=3035)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.country')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.region')),
            ],
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['country'], name='data_buildi_country_e442c7_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['region'], name='data_buildi_region__39c91a_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['city'], name='data_buildi_city_id_612a79_idx'),
        ),
    ]
