# Generated by Django 3.2.15 on 2022-09-21 08:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('id_source', models.CharField(max_length=60)),
                ('height', models.FloatField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('type', models.CharField(choices=[('RE', 'residential'), ('NR', 'non − residential'), ('UN', 'unknown')], default='UN', max_length=2)),
                ('type_source', models.CharField(max_length=50)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=3035)),
            ],
        ),
    ]
