# Generated by Django 3.2.15 on 2022-09-22 18:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_building_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=57)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=3035)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=3035)),
                ('in_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=3035)),
                ('in_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.country')),
                ('in_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.region')),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.city'),
        ),
        migrations.AddField(
            model_name='building',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.country'),
        ),
        migrations.AddField(
            model_name='building',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.region'),
        ),
    ]
