# Generated by Django 3.2.15 on 2022-10-29 11:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0001_init'),
    ]

    operations = [
        migrations.RunSQL('CREATE VIEW data_country_view AS SELECT id, name, geometry FROM public.data_country;')
    ]
