# Generated by Django 3.2.15 on 2022-11-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_country_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='type_source',
            field=models.CharField(max_length=150),
        ),
    ]
