# Generated by Django 3.2.15 on 2022-09-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_country_region_city_added'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['country'], name='buildings_b_country_acb5f2_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['region'], name='buildings_b_region__171609_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['city'], name='buildings_b_city_id_10b7e0_idx'),
        ),
    ]
