# Generated by Django 3.2.15 on 2022-10-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_country_region_city_index_added'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='building',
            name='buildings_b_country_acb5f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='building',
            name='buildings_b_region__171609_idx',
        ),
        migrations.RemoveIndex(
            model_name='building',
            name='buildings_b_city_id_10b7e0_idx',
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=57, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'in_region')},
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('name', 'in_country')},
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['country'], name='data_buildi_country_e442c7_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['region'], name='data_buildi_region__39c91a_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['city'], name='data_buildi_city_id_612a79_idx'),
        ),
    ]
