# Generated by Django 3.2.15 on 2023-02-13 13:04

from django.db import migrations


# creating a read only user for local db access
# https://ubiq.co/database-blog/how-to-create-read-only-user-in-postgresql/

class Migration(migrations.Migration):
    dependencies = [
        ('data', '0003_increase_type_source_len'),
    ]

    operations = [
        migrations.RunSQL('CREATE ROLE readaccess;'),
        migrations.RunSQL('GRANT CONNECT ON DATABASE eubucco TO readaccess;'),
        migrations.RunSQL('GRANT USAGE ON SCHEMA public TO readaccess;'),
        migrations.RunSQL('GRANT SELECT ON ALL TABLES IN SCHEMA public TO readaccess;'),
        migrations.RunSQL("CREATE USER readonly WITH PASSWORD 'readonly';"),
        migrations.RunSQL('GRANT readaccess TO readonly;'),
    ]
