# Generated by Django 3.2.15 on 2023-02-21 11:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0004_readonly'),
    ]

    operations = [
        migrations.RunSQL('ALTER ROLE "readaccess" WITH LOGIN;'),
    ]
