# Generated by Django 3.2.15 on 2023-06-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_readonly_login'),
    ]

    operations = [
        migrations.RunSQL('GRANT pg_read_server_files TO "readonly";'),
        migrations.RunSQL('GRANT pg_write_server_files TO "readonly";'),
    ]
