# Generated by Django 3.2.15 on 2022-10-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_prebuild_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='building',
            name='id_source',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='building',
            name='type_source',
            field=models.CharField(max_length=70),
        ),
    ]
