# Generated by Django 3.2.15 on 2022-10-28 12:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_increase_char_len'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='convex_hull',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=3035),
        ),
    ]
