# Generated by Django 3.2.15 on 2024-09-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_readonly_server_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='version',
            field=models.IntegerField(choices=[(1, 'v0.1'), (2, 'msft24')], default=1),
            preserve_default=False,
        ),
    ]
