# Generated by Django 3.2.15 on 2022-10-28 14:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('data', '0007_add_convex_hull'),
    ]

    operations = [
        migrations.RunSQL('CREATE VIEW data_country_view AS SELECT id, name, geometry FROM public.data_country;')
    ]
