version: '3.2'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}

services:
  dev-django:
    image: eubucco/eubucco.com:dev
    container_name: eubucco_dev_django
    depends_on:
      - postgres
      - redis
    command: /start
    restart: unless-stopped
    volumes:
      - /home/app/eubucco/csvs:/app/csvs
    networks:
      - default
      - proxy
    environment:
      DJANGO_SETTINGS_MODULE: $DJANGO_SETTINGS_MODULE
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      DJANGO_ADMIN_URL: $DJANGO_ADMIN_URL
      DJANGO_ALLOWED_HOSTS: $DJANGO_ALLOWED_HOSTS
      DJANGO_SECURE_SSL_REDIRECT: $DJANGO_SECURE_SSL_REDIRECT
      DJANGO_SERVER_EMAIL: $DJANGO_SERVER_EMAIL
      DJANGO_ACCOUNT_ALLOW_REGISTRATION: $DJANGO_ACCOUNT_ALLOW_REGISTRATION
      WEB_CONCURRENCY: $WEB_CONCURRENCY
      SENTRY_DSN: $SENTRY_DSN
      REDIS_URL: $REDIS_URL
      CELERY_FLOWER_USER: $CELERY_FLOWER_USER
      CELERY_FLOWER_PASSWORD: $CELERY_FLOWER_PASSWORD
      DOMAIN: $DOMAIN
      CELERY_BROKER_URL: $CELERY_BROKER_URL
      API_URL: $API_URL
      DATABASE_URL: $DATABASE_URL
      TILE_URL: $TILE_URL
      DOCS_URL: $DOCS_URL
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dev-django.entrypoints=http"
      - "traefik.http.routers.dev-django.rule=Host(`dev.eubucco.com`)"
      - "traefik.http.middlewares.dev-django-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.dev-django.middlewares=dev-django-https-redirect"
      - "traefik.http.routers.dev-django-secure.entrypoints=https"
      - "traefik.http.routers.dev-django-secure.rule=Host(`dev.eubucco.com`)"
      - "traefik.http.routers.dev-django-secure.tls=true"
      - "traefik.http.routers.dev-django-secure.tls.certresolver=http"
      - "traefik.http.routers.dev-django-secure.service=dev-django"
      - "traefik.http.services.dev-django.loadbalancer.server.port=5000"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.dev-django-secure.middlewares=secHeaders@file"
      - "com.centurylinklabs.watchtower.enable=true"

  dev-api:
    image: eubucco/eubucco.com:dev
    container_name: eubucco_dev_api
    command: /start-api
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - /home/app/eubucco/csvs:/app/csvs
    networks:
      - proxy
      - default
    environment:
      DJANGO_SETTINGS_MODULE: $DJANGO_SETTINGS_MODULE
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      DJANGO_ADMIN_URL: $DJANGO_ADMIN_URL
      DJANGO_ALLOWED_HOSTS: $DJANGO_ALLOWED_HOSTS
      DJANGO_SECURE_SSL_REDIRECT: $DJANGO_SECURE_SSL_REDIRECT
      DJANGO_SERVER_EMAIL: $DJANGO_SERVER_EMAIL
      DJANGO_ACCOUNT_ALLOW_REGISTRATION: $DJANGO_ACCOUNT_ALLOW_REGISTRATION
      WEB_CONCURRENCY: $WEB_CONCURRENCY
      SENTRY_DSN: $SENTRY_DSN
      REDIS_URL: $REDIS_URL
      CELERY_FLOWER_USER: $CELERY_FLOWER_USER
      CELERY_FLOWER_PASSWORD: $CELERY_FLOWER_PASSWORD
      DOMAIN: $DOMAIN
      CELERY_BROKER_URL: $CELERY_BROKER_URL
      API_URL: $API_URL
      DATABASE_URL: $DATABASE_URL
      TILE_URL: $TILE_URL
      DOCS_URL: $DOCS_URL
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dev-api.entrypoints=http"
      - "traefik.http.routers.dev-api.rule=Host(`dev-api.eubucco.com`)"
      - "traefik.http.middlewares.dev-api-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.dev-api.middlewares=dev-api-https-redirect"
      - "traefik.http.routers.dev-api-secure.entrypoints=https"
      - "traefik.http.routers.dev-api-secure.rule=Host(`dev-api.eubucco.com`)"
      - "traefik.http.routers.dev-api-secure.tls=true"
      - "traefik.http.routers.dev-api-secure.tls.certresolver=http"
      - "traefik.http.routers.dev-api-secure.service=dev-api"
      - "traefik.http.services.dev-api.loadbalancer.server.port=8000"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.dev-api-secure.middlewares=secHeaders@file"
      - "com.centurylinklabs.watchtower.enable=true"

  dev-docs:
    image: eubucco/eubucco.com:dev
    container_name: eubucco_dev_docs
    command: /start-docs
    restart: unless-stopped
    networks:
      - proxy
      - default
    environment:
      DJANGO_SETTINGS_MODULE: $DJANGO_SETTINGS_MODULE
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      DJANGO_ADMIN_URL: $DJANGO_ADMIN_URL
      DJANGO_ALLOWED_HOSTS: $DJANGO_ALLOWED_HOSTS
      DJANGO_SECURE_SSL_REDIRECT: $DJANGO_SECURE_SSL_REDIRECT
      DJANGO_SERVER_EMAIL: $DJANGO_SERVER_EMAIL
      DJANGO_ACCOUNT_ALLOW_REGISTRATION: $DJANGO_ACCOUNT_ALLOW_REGISTRATION
      WEB_CONCURRENCY: $WEB_CONCURRENCY
      SENTRY_DSN: $SENTRY_DSN
      REDIS_URL: $REDIS_URL
      CELERY_FLOWER_USER: $CELERY_FLOWER_USER
      CELERY_FLOWER_PASSWORD: $CELERY_FLOWER_PASSWORD
      DOMAIN: $DOMAIN
      CELERY_BROKER_URL: $CELERY_BROKER_URL
      API_URL: $API_URL
      DATABASE_URL: $DATABASE_URL
      TILE_URL: $TILE_URL
      DOCS_URL: $DOCS_URL
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dev-docs.entrypoints=http"
      - "traefik.http.routers.dev-docs.rule=Host(`dev-docs.eubucco.com`)"
      - "traefik.http.middlewares.dev-docs-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.dev-docs.middlewares=dev-docs-https-redirect"
      - "traefik.http.routers.dev-docs-secure.entrypoints=https"
      - "traefik.http.routers.dev-docs-secure.rule=Host(`dev-docs.eubucco.com`)"
      - "traefik.http.routers.dev-docs-secure.tls=true"
      - "traefik.http.routers.dev-docs-secure.tls.certresolver=http"
      - "traefik.http.routers.dev-docs-secure.service=dev-docs"
      - "traefik.http.services.dev-docs.loadbalancer.server.port=8000"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.dev-docs-secure.middlewares=secHeaders@file"
      - "com.centurylinklabs.watchtower.enable=true"

  dev-pg_tileserv:
    image: pramsey/pg_tileserv:latest
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - proxy
      - default
    environment:
      DJANGO_SETTINGS_MODULE: $DJANGO_SETTINGS_MODULE
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      DJANGO_ADMIN_URL: $DJANGO_ADMIN_URL
      DJANGO_ALLOWED_HOSTS: $DJANGO_ALLOWED_HOSTS
      DJANGO_SECURE_SSL_REDIRECT: $DJANGO_SECURE_SSL_REDIRECT
      DJANGO_SERVER_EMAIL: $DJANGO_SERVER_EMAIL
      DJANGO_ACCOUNT_ALLOW_REGISTRATION: $DJANGO_ACCOUNT_ALLOW_REGISTRATION
      WEB_CONCURRENCY: $WEB_CONCURRENCY
      SENTRY_DSN: $SENTRY_DSN
      REDIS_URL: $REDIS_URL
      CELERY_FLOWER_USER: $CELERY_FLOWER_USER
      CELERY_FLOWER_PASSWORD: $CELERY_FLOWER_PASSWORD
      DOMAIN: $DOMAIN
      CELERY_BROKER_URL: $CELERY_BROKER_URL
      API_URL: $API_URL
      DATABASE_URL: $DATABASE_URL
      TILE_URL: $TILE_URL
      DOCS_URL: $DOCS_URL
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dev-pg_tileserv.entrypoints=http"
      - "traefik.http.routers.dev-pg_tileserv.rule=Host(`dev-tiles.eubucco.com`)"
      - "traefik.http.middlewares.dev-pg_tileserv-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.dev-pg_tileserv.middlewares=dev-pg_tileserv-https-redirect"
      - "traefik.http.routers.dev-pg_tileserv-secure.entrypoints=https"
      - "traefik.http.routers.dev-pg_tileserv-secure.rule=Host(`dev-tiles.eubucco.com`)"
      - "traefik.http.routers.dev-pg_tileserv-secure.tls=true"
      - "traefik.http.routers.dev-pg_tileserv-secure.tls.certresolver=http"
      - "traefik.http.routers.dev-pg_tileserv-secure.service=dev-pg_tileserv"
      - "traefik.http.services.dev-pg_tileserv.loadbalancer.server.port=7800"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.dev-pg_tileserv-secure.middlewares=secHeaders@file"

  postgres:
    image: eubucco/postgis:latest
    container_name: dev-db
    restart: unless-stopped
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
      - /home/app/eubucco/export:/export:z
    networks:
      - default
      - dev-db
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      DJANGO_SETTINGS_MODULE: $DJANGO_SETTINGS_MODULE
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      DJANGO_ADMIN_URL: $DJANGO_ADMIN_URL
      DJANGO_ALLOWED_HOSTS: $DJANGO_ALLOWED_HOSTS
      DJANGO_SECURE_SSL_REDIRECT: $DJANGO_SECURE_SSL_REDIRECT
      DJANGO_SERVER_EMAIL: $DJANGO_SERVER_EMAIL
      DJANGO_ACCOUNT_ALLOW_REGISTRATION: $DJANGO_ACCOUNT_ALLOW_REGISTRATION
      WEB_CONCURRENCY: $WEB_CONCURRENCY
      SENTRY_DSN: $SENTRY_DSN
      REDIS_URL: $REDIS_URL
      CELERY_FLOWER_USER: $CELERY_FLOWER_USER
      CELERY_FLOWER_PASSWORD: $CELERY_FLOWER_PASSWORD
      DOMAIN: $DOMAIN
      CELERY_BROKER_URL: $CELERY_BROKER_URL
      API_URL: $API_URL
      DATABASE_URL: $DATABASE_URL
      TILE_URL: $TILE_URL
      DOCS_URL: $DOCS_URL
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

  redis:
    image: redis:6
    restart: unless-stopped
    networks:
      - default

  celeryworker:
    image: eubucco/eubucco.com:dev
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    volumes:
      - /home/app/eubucco/csvs:/app/csvs
    environment:
      DJANGO_SETTINGS_MODULE: $DJANGO_SETTINGS_MODULE
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      DJANGO_ADMIN_URL: $DJANGO_ADMIN_URL
      DJANGO_ALLOWED_HOSTS: $DJANGO_ALLOWED_HOSTS
      DJANGO_SECURE_SSL_REDIRECT: $DJANGO_SECURE_SSL_REDIRECT
      DJANGO_SERVER_EMAIL: $DJANGO_SERVER_EMAIL
      DJANGO_ACCOUNT_ALLOW_REGISTRATION: $DJANGO_ACCOUNT_ALLOW_REGISTRATION
      WEB_CONCURRENCY: $WEB_CONCURRENCY
      SENTRY_DSN: $SENTRY_DSN
      REDIS_URL: $REDIS_URL
      CELERY_FLOWER_USER: $CELERY_FLOWER_USER
      CELERY_FLOWER_PASSWORD: $CELERY_FLOWER_PASSWORD
      DOMAIN: $DOMAIN
      CELERY_BROKER_URL: $CELERY_BROKER_URL
      API_URL: $API_URL
      DATABASE_URL: $DATABASE_URL
      TILE_URL: $TILE_URL
      DOCS_URL: $DOCS_URL
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    command: /start-celeryworker
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  celerybeat:
    image: eubucco/eubucco.com:dev
    depends_on:
      - postgres
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: $DJANGO_SETTINGS_MODULE
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      DJANGO_ADMIN_URL: $DJANGO_ADMIN_URL
      DJANGO_ALLOWED_HOSTS: $DJANGO_ALLOWED_HOSTS
      DJANGO_SECURE_SSL_REDIRECT: $DJANGO_SECURE_SSL_REDIRECT
      DJANGO_SERVER_EMAIL: $DJANGO_SERVER_EMAIL
      DJANGO_ACCOUNT_ALLOW_REGISTRATION: $DJANGO_ACCOUNT_ALLOW_REGISTRATION
      WEB_CONCURRENCY: $WEB_CONCURRENCY
      SENTRY_DSN: $SENTRY_DSN
      REDIS_URL: $REDIS_URL
      CELERY_FLOWER_USER: $CELERY_FLOWER_USER
      CELERY_FLOWER_PASSWORD: $CELERY_FLOWER_PASSWORD
      DOMAIN: $DOMAIN
      CELERY_BROKER_URL: $CELERY_BROKER_URL
      API_URL: $API_URL
      DATABASE_URL: $DATABASE_URL
      TILE_URL: $TILE_URL
      DOCS_URL: $DOCS_URL
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    command: /start-celerybeat
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  dev-flower:
    image: eubucco/eubucco.com:dev
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    networks:
      - proxy
      - default
    environment:
      DJANGO_SETTINGS_MODULE: $DJANGO_SETTINGS_MODULE
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      DJANGO_ADMIN_URL: $DJANGO_ADMIN_URL
      DJANGO_ALLOWED_HOSTS: $DJANGO_ALLOWED_HOSTS
      DJANGO_SECURE_SSL_REDIRECT: $DJANGO_SECURE_SSL_REDIRECT
      DJANGO_SERVER_EMAIL: $DJANGO_SERVER_EMAIL
      DJANGO_ACCOUNT_ALLOW_REGISTRATION: $DJANGO_ACCOUNT_ALLOW_REGISTRATION
      WEB_CONCURRENCY: $WEB_CONCURRENCY
      SENTRY_DSN: $SENTRY_DSN
      REDIS_URL: $REDIS_URL
      CELERY_FLOWER_USER: $CELERY_FLOWER_USER
      CELERY_FLOWER_PASSWORD: $CELERY_FLOWER_PASSWORD
      DOMAIN: $DOMAIN
      CELERY_BROKER_URL: $CELERY_BROKER_URL
      API_URL: $API_URL
      DATABASE_URL: $DATABASE_URL
      TILE_URL: $TILE_URL
      DOCS_URL: $DOCS_URL
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    command: /start-flower
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dev-flower.entrypoints=http"
      - "traefik.http.routers.dev-flower.rule=Host(`dev-tasks.eubucco.com`)"
      - "traefik.http.middlewares.dev-flower-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.dev-flower.middlewares=dev-flower-https-redirect"
      - "traefik.http.routers.dev-flower-secure.entrypoints=https"
      - "traefik.http.routers.dev-flower-secure.rule=Host(`dev-tasks.eubucco.com`)"
      - "traefik.http.routers.dev-flower-secure.tls=true"
      - "traefik.http.routers.dev-flower-secure.tls.certresolver=http"
      - "traefik.http.routers.dev-flower-secure.service=dev-flower"
      - "traefik.http.services.dev-flower.loadbalancer.server.port=5555"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.dev-flower-secure.middlewares=secHeaders@file"
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  default:
  proxy:
    external: true
  dev-db:
    name: dev-db
