version: '3.2'

volumes:
  production_postgres_data: { }
  production_postgres_data_backups: { }
  production_traefik: { }

services:
  django:
    image: eubucco/eubucco.com:latest
    depends_on:
      - postgres
      - redis
    command: /start
    restart: unless-stopped
    volumes:
      - /home/app/eubucco/csvs:/app/csvs
    networks:
      - default
      - proxy
    environment:
      DJANGO_SETTINGS_MODULE: $DJANGO_SETTINGS_MODULE
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      DJANGO_ADMIN_URL: $DJANGO_ADMIN_URL
      DJANGO_ALLOWED_HOSTS: $DJANGO_ALLOWED_HOSTS
      DJANGO_SECURE_SSL_REDIRECT: $DJANGO_SECURE_SSL_REDIRECT
      DJANGO_SERVER_EMAIL: $DJANGO_SERVER_EMAIL
      DJANGO_ACCOUNT_ALLOW_REGISTRATION: $DJANGO_ACCOUNT_ALLOW_REGISTRATION
      WEB_CONCURRENCY: $WEB_CONCURRENCY
      SENTRY_DSN: $SENTRY_DSN
      REDIS_URL: $REDIS_URL
      CELERY_FLOWER_USER: $CELERY_FLOWER_USER
      CELERY_FLOWER_PASSWORD: $CELERY_FLOWER_PASSWORD
      DOMAIN: $DOMAIN
      CELERY_BROKER_URL: $CELERY_BROKER_URL
      API_URL: $API_URL
      DATABASE_URL: $DATABASE_URL
      TILE_URL: $TILE_URL
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.entrypoints=http"
      - "traefik.http.routers.django.rule=Host(`dev.eubucco.com`)"
      - "traefik.http.middlewares.django-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.django.middlewares=django-https-redirect"
      - "traefik.http.routers.django-secure.entrypoints=https"
      - "traefik.http.routers.django-secure.rule=Host(`dev.eubucco.com`)"
      - "traefik.http.routers.django-secure.tls=true"
      - "traefik.http.routers.django-secure.tls.certresolver=http"
      - "traefik.http.routers.django-secure.service=django"
      - "traefik.http.services.django.loadbalancer.server.port=5000"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.django-secure.middlewares=secHeaders@file"

  api:
    image: eubucco/eubucco.com:latest
    container_name: eubucco_production_api
    command: /start-api
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - /home/app/eubucco/csvs:/app/csvs
    networks:
      - proxy
      - default
    environment:
      DJANGO_SETTINGS_MODULE: $DJANGO_SETTINGS_MODULE
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      DJANGO_ADMIN_URL: $DJANGO_ADMIN_URL
      DJANGO_ALLOWED_HOSTS: $DJANGO_ALLOWED_HOSTS
      DJANGO_SECURE_SSL_REDIRECT: $DJANGO_SECURE_SSL_REDIRECT
      DJANGO_SERVER_EMAIL: $DJANGO_SERVER_EMAIL
      DJANGO_ACCOUNT_ALLOW_REGISTRATION: $DJANGO_ACCOUNT_ALLOW_REGISTRATION
      WEB_CONCURRENCY: $WEB_CONCURRENCY
      SENTRY_DSN: $SENTRY_DSN
      REDIS_URL: $REDIS_URL
      CELERY_FLOWER_USER: $CELERY_FLOWER_USER
      CELERY_FLOWER_PASSWORD: $CELERY_FLOWER_PASSWORD
      DOMAIN: $DOMAIN
      CELERY_BROKER_URL: $CELERY_BROKER_URL
      API_URL: $API_URL
      DATABASE_URL: $DATABASE_URL
      TILE_URL: $TILE_URL
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=http"
      - "traefik.http.routers.api.rule=Host(`dev-api.eubucco.com`)"
      - "traefik.http.middlewares.api-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.api.middlewares=api-https-redirect"
      - "traefik.http.routers.api-secure.entrypoints=https"
      - "traefik.http.routers.api-secure.rule=Host(`dev-api.eubucco.com`)"
      - "traefik.http.routers.api-secure.tls=true"
      - "traefik.http.routers.api-secure.tls.certresolver=http"
      - "traefik.http.routers.api-secure.service=api"
      - "traefik.http.services.api.loadbalancer.server.port=8000"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.api-secure.middlewares=secHeaders@file"


  pg_tileserv:
    image: pramsey/pg_tileserv:latest
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - proxy
      - default
    environment:
      DJANGO_SETTINGS_MODULE: $DJANGO_SETTINGS_MODULE
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      DJANGO_ADMIN_URL: $DJANGO_ADMIN_URL
      DJANGO_ALLOWED_HOSTS: $DJANGO_ALLOWED_HOSTS
      DJANGO_SECURE_SSL_REDIRECT: $DJANGO_SECURE_SSL_REDIRECT
      DJANGO_SERVER_EMAIL: $DJANGO_SERVER_EMAIL
      DJANGO_ACCOUNT_ALLOW_REGISTRATION: $DJANGO_ACCOUNT_ALLOW_REGISTRATION
      WEB_CONCURRENCY: $WEB_CONCURRENCY
      SENTRY_DSN: $SENTRY_DSN
      REDIS_URL: $REDIS_URL
      CELERY_FLOWER_USER: $CELERY_FLOWER_USER
      CELERY_FLOWER_PASSWORD: $CELERY_FLOWER_PASSWORD
      DOMAIN: $DOMAIN
      CELERY_BROKER_URL: $CELERY_BROKER_URL
      API_URL: $API_URL
      DATABASE_URL: $DATABASE_URL
      TILE_URL: $TILE_URL
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pg_tileserv.entrypoints=http"
      - "traefik.http.routers.pg_tileserv.rule=Host(`dev-tiles.eubucco.com`)"
      - "traefik.http.middlewares.pg_tileserv-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.pg_tileserv.middlewares=pg_tileserv-https-redirect"
      - "traefik.http.routers.pg_tileserv-secure.entrypoints=https"
      - "traefik.http.routers.pg_tileserv-secure.rule=Host(`dev-tiles.eubucco.com`)"
      - "traefik.http.routers.pg_tileserv-secure.tls=true"
      - "traefik.http.routers.pg_tileserv-secure.tls.certresolver=http"
      - "traefik.http.routers.pg_tileserv-secure.service=pg_tileserv"
      - "traefik.http.services.pg_tileserv.loadbalancer.server.port=7800"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.pg_tileserv-secure.middlewares=secHeaders@file"

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: eubucco_production_postgres
    restart: unless-stopped
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    networks:
      - default
    environment:
      DJANGO_SETTINGS_MODULE: $DJANGO_SETTINGS_MODULE
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      DJANGO_ADMIN_URL: $DJANGO_ADMIN_URL
      DJANGO_ALLOWED_HOSTS: $DJANGO_ALLOWED_HOSTS
      DJANGO_SECURE_SSL_REDIRECT: $DJANGO_SECURE_SSL_REDIRECT
      DJANGO_SERVER_EMAIL: $DJANGO_SERVER_EMAIL
      DJANGO_ACCOUNT_ALLOW_REGISTRATION: $DJANGO_ACCOUNT_ALLOW_REGISTRATION
      WEB_CONCURRENCY: $WEB_CONCURRENCY
      SENTRY_DSN: $SENTRY_DSN
      REDIS_URL: $REDIS_URL
      CELERY_FLOWER_USER: $CELERY_FLOWER_USER
      CELERY_FLOWER_PASSWORD: $CELERY_FLOWER_PASSWORD
      DOMAIN: $DOMAIN
      CELERY_BROKER_URL: $CELERY_BROKER_URL
      API_URL: $API_URL
      DATABASE_URL: $DATABASE_URL
      TILE_URL: $TILE_URL
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

  redis:
    image: redis:6
    restart: unless-stopped
    networks:
      - default

  celeryworker:
    image: eubucco/eubucco.com:latest
    restart: unless-stopped
    environment:
      DJANGO_SETTINGS_MODULE: $DJANGO_SETTINGS_MODULE
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      DJANGO_ADMIN_URL: $DJANGO_ADMIN_URL
      DJANGO_ALLOWED_HOSTS: $DJANGO_ALLOWED_HOSTS
      DJANGO_SECURE_SSL_REDIRECT: $DJANGO_SECURE_SSL_REDIRECT
      DJANGO_SERVER_EMAIL: $DJANGO_SERVER_EMAIL
      DJANGO_ACCOUNT_ALLOW_REGISTRATION: $DJANGO_ACCOUNT_ALLOW_REGISTRATION
      WEB_CONCURRENCY: $WEB_CONCURRENCY
      SENTRY_DSN: $SENTRY_DSN
      REDIS_URL: $REDIS_URL
      CELERY_FLOWER_USER: $CELERY_FLOWER_USER
      CELERY_FLOWER_PASSWORD: $CELERY_FLOWER_PASSWORD
      DOMAIN: $DOMAIN
      CELERY_BROKER_URL: $CELERY_BROKER_URL
      API_URL: $API_URL
      DATABASE_URL: $DATABASE_URL
      TILE_URL: $TILE_URL
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    command: /start-celeryworker

  celerybeat:
    image: eubucco/eubucco.com:latest
    environment:
      DJANGO_SETTINGS_MODULE: $DJANGO_SETTINGS_MODULE
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      DJANGO_ADMIN_URL: $DJANGO_ADMIN_URL
      DJANGO_ALLOWED_HOSTS: $DJANGO_ALLOWED_HOSTS
      DJANGO_SECURE_SSL_REDIRECT: $DJANGO_SECURE_SSL_REDIRECT
      DJANGO_SERVER_EMAIL: $DJANGO_SERVER_EMAIL
      DJANGO_ACCOUNT_ALLOW_REGISTRATION: $DJANGO_ACCOUNT_ALLOW_REGISTRATION
      WEB_CONCURRENCY: $WEB_CONCURRENCY
      SENTRY_DSN: $SENTRY_DSN
      REDIS_URL: $REDIS_URL
      CELERY_FLOWER_USER: $CELERY_FLOWER_USER
      CELERY_FLOWER_PASSWORD: $CELERY_FLOWER_PASSWORD
      DOMAIN: $DOMAIN
      CELERY_BROKER_URL: $CELERY_BROKER_URL
      API_URL: $API_URL
      DATABASE_URL: $DATABASE_URL
      TILE_URL: $TILE_URL
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    command: /start-celerybeat

  flower:
    image: eubucco/eubucco.com:latest
    restart: unless-stopped
    environment:
      DJANGO_SETTINGS_MODULE: $DJANGO_SETTINGS_MODULE
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      DJANGO_ADMIN_URL: $DJANGO_ADMIN_URL
      DJANGO_ALLOWED_HOSTS: $DJANGO_ALLOWED_HOSTS
      DJANGO_SECURE_SSL_REDIRECT: $DJANGO_SECURE_SSL_REDIRECT
      DJANGO_SERVER_EMAIL: $DJANGO_SERVER_EMAIL
      DJANGO_ACCOUNT_ALLOW_REGISTRATION: $DJANGO_ACCOUNT_ALLOW_REGISTRATION
      WEB_CONCURRENCY: $WEB_CONCURRENCY
      SENTRY_DSN: $SENTRY_DSN
      REDIS_URL: $REDIS_URL
      CELERY_FLOWER_USER: $CELERY_FLOWER_USER
      CELERY_FLOWER_PASSWORD: $CELERY_FLOWER_PASSWORD
      DOMAIN: $DOMAIN
      CELERY_BROKER_URL: $CELERY_BROKER_URL
      API_URL: $API_URL
      DATABASE_URL: $DATABASE_URL
      TILE_URL: $TILE_URL
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    command: /start-flower
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flower.entrypoints=http"
      - "traefik.http.routers.flower.rule=Host(`dev-tasks.eubucco.com`)"
      - "traefik.http.middlewares.flower-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.flower.middlewares=flower-https-redirect"
      - "traefik.http.routers.flower-secure.entrypoints=https"
      - "traefik.http.routers.flower-secure.rule=Host(`dev-tasks.eubucco.com`)"
      - "traefik.http.routers.flower-secure.tls=true"
      - "traefik.http.routers.flower-secure.tls.certresolver=http"
      - "traefik.http.routers.flower-secure.service=flower"
      - "traefik.http.services.flower.loadbalancer.server.port=5555"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.flower-secure.middlewares=secHeaders@file"

networks:
  default:
  proxy:
    external: true
