version: '3.2'
name: eubucco-dev

volumes:
  postgres_data: {}
  postgres_data_backups: {}
  minio_data: {}

services:
  django:
    image: eubucco/eubucco.com:dev
    depends_on:
      - postgres
      - redis
      - minio
    command: /start
    restart: unless-stopped
    volumes:
      - /home/eubucco-data:/app/data
    networks:
      - default
      - proxy
    env_file:
      - .envs/.dev/.django
      - .envs/.dev/.postgres
      - .envs/.dev/.minio
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dev-django.entrypoints=http"
      - "traefik.http.routers.dev-django.rule=Host(`dev.eubucco.com`)"
      - "traefik.http.middlewares.dev-django-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.dev-django.middlewares=dev-django-https-redirect"
      - "traefik.http.routers.dev-django-secure.entrypoints=https"
      - "traefik.http.routers.dev-django-secure.rule=Host(`dev.eubucco.com`)"
      - "traefik.http.routers.dev-django-secure.tls=true"
      - "traefik.http.routers.dev-django-secure.tls.certresolver=http"
      - "traefik.http.routers.dev-django-secure.service=dev-django"
      - "traefik.http.services.dev-django.loadbalancer.server.port=5000"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.dev-django-secure.middlewares=secHeaders@file"
      - "com.centurylinklabs.watchtower.enable=true"

  api:
    image: eubucco/eubucco.com:dev
    container_name: eubucco_dev_api
    command: /start-api
    depends_on:
      - postgres
      - minio
    restart: unless-stopped
    volumes:
      - /home/eubucco-data:/app/data
    networks:
      - proxy
      - default
    env_file:
      - .envs/.dev/.django
      - .envs/.dev/.postgres
      - .envs/.dev/.minio
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dev-api.entrypoints=http"
      - "traefik.http.routers.dev-api.rule=Host(`dev-api.eubucco.com`)"
      - "traefik.http.middlewares.dev-api-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.dev-api.middlewares=dev-api-https-redirect"
      - "traefik.http.routers.dev-api-secure.entrypoints=https"
      - "traefik.http.routers.dev-api-secure.rule=Host(`dev-api.eubucco.com`)"
      - "traefik.http.routers.dev-api-secure.tls=true"
      - "traefik.http.routers.dev-api-secure.tls.certresolver=http"
      - "traefik.http.routers.dev-api-secure.service=dev-api"
      - "traefik.http.services.dev-api.loadbalancer.server.port=8000"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.dev-api-secure.middlewares=secHeaders@file"
      - "com.centurylinklabs.watchtower.enable=true"

  docs:
    image: eubucco/eubucco-docs:latest
    container_name: eubucco_dev_docs
    restart: unless-stopped
    networks:
      - proxy
      - default
    env_file:
      - .envs/.dev/.django
      - .envs/.dev/.postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dev-docs.entrypoints=http"
      - "traefik.http.routers.dev-docs.rule=Host(`dev-docs.eubucco.com`)"
      - "traefik.http.middlewares.dev-docs-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.dev-docs.middlewares=dev-docs-https-redirect"
      - "traefik.http.routers.dev-docs-secure.entrypoints=https"
      - "traefik.http.routers.dev-docs-secure.rule=Host(`dev-docs.eubucco.com`)"
      - "traefik.http.routers.dev-docs-secure.tls=true"
      - "traefik.http.routers.dev-docs-secure.tls.certresolver=http"
      - "traefik.http.routers.dev-docs-secure.service=dev-docs"
      - "traefik.http.services.dev-docs.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.dev-docs-secure.middlewares=secHeaders@file"
      - "com.centurylinklabs.watchtower.enable=true"

  # pg_tileserv:
  #   image: pramsey/pg_tileserv:latest
  #   depends_on:
  #     - postgres
  #   restart: unless-stopped
  #   networks:
  #     - proxy
  #     - default
  #   env_file:
  #     - .envs/.dev/.postgres
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.dev-pg_tileserv.entrypoints=http"
  #     - "traefik.http.routers.dev-pg_tileserv.rule=Host(`dev-tiles.eubucco.com`)"
  #     - "traefik.http.middlewares.dev-pg_tileserv-https-redirect.redirectscheme.scheme=https"
  #     - "traefik.http.routers.dev-pg_tileserv.middlewares=dev-pg_tileserv-https-redirect"
  #     - "traefik.http.routers.dev-pg_tileserv-secure.entrypoints=https"
  #     - "traefik.http.routers.dev-pg_tileserv-secure.rule=Host(`dev-tiles.eubucco.com`)"
  #     - "traefik.http.routers.dev-pg_tileserv-secure.tls=true"
  #     - "traefik.http.routers.dev-pg_tileserv-secure.tls.certresolver=http"
  #     - "traefik.http.routers.dev-pg_tileserv-secure.service=dev-pg_tileserv"
  #     - "traefik.http.services.dev-pg_tileserv.loadbalancer.server.port=7800"
  #     - "traefik.docker.network=proxy"
  #     - "traefik.http.routers.dev-pg_tileserv-secure.middlewares=secHeaders@file"

  postgres:
    image: eubucco/postgis:latest
    container_name: dev-db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
      - postgres_data_backups:/backups:z
      - /home/app/eubucco/export:/export
    networks:
      - default
      - dev-db
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - .envs/.dev/.postgres

  redis:
    image: redis:6
    restart: unless-stopped
    networks:
      - default

  celeryworker-io:
    image: eubucco/eubucco.com:dev
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
      - minio
    env_file:
      - .envs/.dev/.django
      - .envs/.dev/.postgres
      - .envs/.dev/.minio
    volumes:
      - /home/eubucco-data:/app/data
    command: /start-celeryworker-io
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - default
      - dev-db

  celeryworker-heavy:
    image: eubucco/eubucco.com:dev
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
      - minio
    env_file:
      - .envs/.dev/.django
      - .envs/.dev/.postgres
      - .envs/.dev/.minio
    volumes:
      - /home/eubucco-data:/app/data
    command: /start-celeryworker-heavy
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - default
      - dev-db

  celerybeat:
    image: eubucco/eubucco.com:dev
    depends_on:
      - postgres
      - redis
      - minio
    env_file:
      - .envs/.dev/.django
      - .envs/.dev/.postgres
      - .envs/.dev/.minio
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - default
      - dev-db

  flower:
    image: eubucco/eubucco.com:dev
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    networks:
      - proxy
      - default
    env_file:
      - .envs/.dev/.django
      - .envs/.dev/.postgres
    command: /start-flower
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dev-flower.entrypoints=http"
      - "traefik.http.routers.dev-flower.rule=Host(`dev-tasks.eubucco.com`)"
      - "traefik.http.middlewares.dev-flower-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.dev-flower.middlewares=dev-flower-https-redirect"
      - "traefik.http.routers.dev-flower-secure.entrypoints=https"
      - "traefik.http.routers.dev-flower-secure.rule=Host(`dev-tasks.eubucco.com`)"
      - "traefik.http.routers.dev-flower-secure.tls=true"
      - "traefik.http.routers.dev-flower-secure.tls.certresolver=http"
      - "traefik.http.routers.dev-flower-secure.service=dev-flower"
      - "traefik.http.services.dev-flower.loadbalancer.server.port=5555"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.dev-flower-secure.middlewares=secHeaders@file"
      - "com.centurylinklabs.watchtower.enable=true"

  minio:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    restart: unless-stopped
    env_file:
      - .envs/.dev/.minio
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
      - /home/app/eubucco/tiles:/tiles:ro
    networks:
      - default
      - proxy
    ports:
      - "9000:9000"
      - "9001:9001"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      # ===================================
      # S3 API on dev-s3.eubucco.com
      # ===================================
      - "traefik.http.routers.dev-minio.entrypoints=http"
      - "traefik.http.routers.dev-minio.rule=Host(`dev-s3.eubucco.com`)"
      - "traefik.http.middlewares.dev-minio-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.dev-minio.middlewares=dev-minio-https-redirect"
      - "traefik.http.routers.dev-minio-secure.entrypoints=https"
      - "traefik.http.routers.dev-minio-secure.rule=Host(`dev-s3.eubucco.com`)"
      - "traefik.http.routers.dev-minio-secure.tls=true"
      - "traefik.http.routers.dev-minio-secure.tls.certresolver=http"
      - "traefik.http.routers.dev-minio-secure.middlewares=secHeaders@file"
      - "traefik.http.routers.dev-minio-secure.service=dev-minio"
      - "traefik.http.services.dev-minio.loadbalancer.server.port=9000"

      # ===================================
      # Console on dev-minio-console.eubucco.com
      # ===================================
      - "traefik.http.routers.dev-minio-console.entrypoints=http"
      - "traefik.http.routers.dev-minio-console.rule=Host(`dev-minio-console.eubucco.com`)"
      - "traefik.http.middlewares.dev-minio-console-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.dev-minio-console.middlewares=dev-minio-console-https-redirect"

      - "traefik.http.routers.dev-minio-console-secure.entrypoints=https"
      - "traefik.http.routers.dev-minio-console-secure.rule=Host(`dev-minio-console.eubucco.com`)"
      - "traefik.http.routers.dev-minio-console-secure.tls=true"
      - "traefik.http.routers.dev-minio-console-secure.tls.certresolver=http"
      - "traefik.http.routers.dev-minio-console-secure.middlewares=secHeaders@file"
      - "traefik.http.routers.dev-minio-console-secure.service=dev-minio-console"
      - "traefik.http.services.dev-minio-console.loadbalancer.server.port=9001"

  minio-setup:
    image: minio/mc:RELEASE.2024-05-09T17-04-24Z
    depends_on:
      - minio
    env_file:
      - .envs/.dev/.minio
    entrypoint: |
      /bin/sh -c "
      # 1. Connect to local MinIO
      until (/usr/bin/mc alias set localminio http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD}); do
        echo 'waiting for minio...' && sleep 1;
      done;

      # 2. Configure the Webhook Target (The Plausible Bridge)
      echo 'Configuring Plausible webhook...'
      /usr/bin/mc admin config set localminio audit_webhook:plausible \
        endpoint=\"http://django:8000/data/webhook/minio/\" \
        auth_token=\"$${MINIO_WEBHOOK_AUTH_TOKEN}\";

      # 3. Restart MinIO to register the new SQS ARN
      echo 'Restarting MinIO to apply webhook config...'
      /usr/bin/mc admin service restart localminio;

      # Wait a moment for MinIO to come back online after restart
      sleep 3;

      # 4. Create Bucket and Set Permissions
      /usr/bin/mc mb -p localminio/$${MINIO_BUCKET};
      /usr/bin/mc anonymous set download localminio/$${MINIO_BUCKET};

      # 5. Seed initial data
      if [ -f /tiles/nuts.pmtiles ]; then
        /usr/bin/mc cp /tiles/nuts.pmtiles localminio/$${MINIO_BUCKET}/$${NUTS_PM_TILES_OBJECT};
      fi;

      # 6. Subscribe the Bucket to the Webhook
      echo 'Adding bucket event notification...'
      /usr/bin/mc event add localminio/$${MINIO_BUCKET} arn:minio:sqs::plausible:webhook --event get || true;

      echo 'MinIO setup complete.'
      "
    volumes:
      - /home/eubucco/tiles:/tiles:ro

networks:
  default:
  proxy:
    external: true
  dev-db:
    name: dev-db
