version: '3'
name: eubucco_local

volumes:
  postgres_data: { }
  postgres_data_backups: { }
  data_dumps: { }
  minio_data: { }

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django
    platform: linux/x86_64
    volumes:
      - .:/app:z
      - data_dumps:/dumps
    depends_on:
      - postgres
      - redis
      - mailhog
      - minio
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.envs/.local/.minio
    ports:
      - "8000:8000"
    command: /start

  api:
    <<: *django
    volumes:
      - ./data:/app/data
    depends_on:
      - postgres
      - minio
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.envs/.local/.minio
    ports:
      - "8001:8001"
    command: /start-api

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: eubucco_production_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
      - postgres_data_backups:/backups:z
      - data_dumps:/dumps
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"

  # pg_tileserv:
  #   image: pramsey/pg_tileserv:latest
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - ./.envs/.local/.django
  #     - ./.envs/.local/.postgres
  #   ports:
  #     - "7800:7800"

  docs:
    image: eubucco/eubucco-docs:latest
    restart: unless-stopped
    ports:
      - "9090:80"

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  celeryworker-io:
    <<: *django
    image: celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
      - minio
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.envs/.local/.minio
    ports: []
    command: /start-celeryworker-io

  celeryworker-heavy:
    <<: *django
    image: celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
      - minio
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.envs/.local/.minio
    ports: []
    command: /start-celeryworker-heavy

  celerybeat:
    <<: *django
    image: celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
      - minio
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.envs/.local/.minio
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: flower
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "5555:5555"
    command: /start-flower

  tailwind:
    <<: *django
    image: tailwind
    # Without tty, no stdin, and tailwind watcher aborts
    # https://github.com/tailwindlabs/tailwindcss/issues/5324
    tty: true
    ports: []
    command: /start-tailwind

  minio:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    volumes:
      - minio_data:/data
      - ./tiles:/tiles:ro
    env_file:
      - ./.envs/.local/.minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

  minio-setup:
    image: minio/mc:RELEASE.2024-05-09T17-04-24Z
    volumes:
      - ./tiles:/tiles:ro
    depends_on:
      - minio
    env_file:
      - ./.envs/.local/.minio
    entrypoint: |
      /bin/sh -c "
      until (/usr/bin/mc alias set localminio http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD}); do echo 'waiting for minio...' && sleep 1; done;
      /usr/bin/mc mb -p localminio/$${MINIO_BUCKET};
      /usr/bin/mc anonymous set download localminio/$${MINIO_BUCKET};
      if [ -f /tiles/nuts.pmtiles ]; then /usr/bin/mc cp /tiles/nuts.pmtiles localminio/$${MINIO_BUCKET}/$${NUTS_PM_TILES_OBJECT}; fi;
      "
