version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: eubucco_production_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    volumes:
      - ./csvs:/app/csvs

  api:
    build:
      context: .
      dockerfile: compose/local/fastapi/Dockerfile
    container_name: eubucco_production_api
    depends_on:
      - postgres
    env_file:
      - ./.envs/.production/.django
    volumes:
      - ./csvs:/app/csvs

  pg_tileserv:
    image: pramsey/pg_tileserv:latest
    container_name: eubucco_local_pg_tileserv
    env_file:
      - ./.envs/.production/.django
    depends_on:
      - postgres

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: eubucco_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: eubucco_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"

  redis:
    image: redis:6

  celeryworker:
    <<: *django
    image: eubucco_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: eubucco_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: eubucco_production_flower
    command: /start-flower
