# Generated by Django 3.2.15 on 2022-10-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('csv_path', models.FilePathField()),
                ('csv_size_in_mb', models.FloatField()),
                ('gpkg_path', models.FilePathField()),
                ('gpkg_size_in_mb', models.FloatField()),
            ],
        ),
    ]
