# Generated by Django 3.2.15 on 2022-09-29 13:01

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=30)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField(max_length=600)),
                ('text', martor.models.MartorField()),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
