# Generated by Django 3.2.15 on 2022-09-25 15:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
