# Generated by Django 3.2.15 on 2022-10-26 14:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ingested_on', models.DateTimeField(auto_now_add=True)),
                ('size_in_mb', models.FloatField()),
                ('path', models.FilePathField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('BU', 'building'), ('EX', 'example'), ('AD', 'additional')], db_index=True, max_length=2)),
            ],
        ),
    ]
