# Generated by Django 3.2.15 on 2022-10-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='info',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
