# Generated by Django 3.2.15 on 2024-09-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='version',
            field=models.IntegerField(choices=[(1, 'v0.1'), (2, 'msft24')], default=1),
            preserve_default=False,
        ),
    ]
