# Generated by Django 3.2.15 on 2025-12-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='version',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
