version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/app/.docker/config.json:/config.json
    command: --interval 60 --cleanup --label-enable
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
