# Generated by Django 3.2.15 on 2022-09-26 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0003_country_region_city_index_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dump',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('requested_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('is_done', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=30)),
                ('url', models.URLField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('cities', models.ManyToManyField(to='data.City')),
                ('countries', models.ManyToManyField(to='data.Country')),
                ('regions', models.ManyToManyField(to='data.Region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
