#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Create minified tailwindcss stylesheet
#python /app/manage.py tailwind build

python /app/manage.py collectstatic --noinput

/usr/local/bin/gunicorn config.asgi --bind 0.0.0.0:5000 --chdir=/app -k uvicorn.workers.UvicornWorker
