#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Create minified tailwindcss stylesheet
python manage.py tailwind install
python manage.py tailwind build

# Migrate Database
python manage.py migrate

# Prepare static files
python manage.py collectstatic --noinput

/usr/local/bin/gunicorn config.asgi --bind 0.0.0.0:5000 --chdir=/app -k uvicorn.workers.UvicornWorker
