version: "3.3"
services:
  mail:
    image: bytemark/smtp
    restart: always

  plausible_db:
    # supported versions are 12, 13, and 14
    image: postgres:14-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - default
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

  plausible_events_db:
    image: clickhouse/clickhouse-server:22.6-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    networks:
      - default
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:latest
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    networks:
      - default
      - proxy
    environment:
      ADMIN_USER_EMAIL: $ADMIN_USER_EMAIL
      ADMIN_USER_NAME: $ADMIN_USER_NAME
      ADMIN_USER_PWD: $ADMIN_USER_PWD
      BASE_URL: $BASE_URL
      SECRET_KEY_BASE: $SECRET_KEY_BASE
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plausible.entrypoints=http"
      - "traefik.http.routers.plausible.rule=Host(`analytics.eubucco.com`)"
      - "traefik.http.middlewares.plausible-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.plausible.middlewares=plausible-https-redirect"
      - "traefik.http.routers.plausible-secure.entrypoints=https"
      - "traefik.http.routers.plausible-secure.rule=Host(`analytics.eubucco.com`)"
      - "traefik.http.routers.plausible-secure.tls=true"
      - "traefik.http.routers.plausible-secure.tls.certresolver=http"
      - "traefik.http.routers.plausible-secure.service=plausible"
      - "traefik.http.services.plausible.loadbalancer.server.port=8000"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.plausible-secure.middlewares=secHeaders@file"


volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  geoip:
    driver: local

networks:
  default:
  proxy:
    external: true
